spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/syscal
    username: root
    password: sa..
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host : smtp.gmail.com
    port : 587
    username : edwarerazo321@gmail.com #email para enviar
    password : dymcqzdxhppdturl #contraseña de aplicación
    properties:
      mail:
        smtp:
          starttls:
            enable : true
            required : true
          auth : true
          connectiontimeout : 5000
          timeout : 5000
          writetimeout : 5000
server:
  port: 8090 # This is the default port anyway, but you can change it here
security:

jwt:
  jwtCookieName: Bearer
  jwtSecret: zdWIiOiJlZHdhcmVyYXpvIiwiaWF0IjoxNjY3NTM4NTQxLCJleHAiOjE2Njc2MjQ5NDF9
  jwtExpirationMs: 86400000
